import { createDefaultEngineState } from '../store/synthStore';
import type { SampleLayerState } from '../types/soundfont';
import { expandedFactoryPresets } from './expandedFactoryPresets';
import type {
  EffectState,
  EffectType,
  EnvelopeState,
  FilterState,
  LfoState,
  NoiseState,
  OscillatorState,
  SubOscillatorState,
  SynthEngineState,
  SynthPreset,
  VectorMixerState,
  WaveSequencerState,
} from '../types/synth';

type PresetCategory = SynthPreset['category'];

type EngineOverrides = Omit<
  Partial<SynthEngineState>,
  | 'oscA'
  | 'oscB'
  | 'subOsc'
  | 'noise'
  | 'filter'
  | 'ampEnv'
  | 'filterEnv'
  | 'lfo1'
  | 'lfo2'
  | 'waveSequencer'
  | 'vectorMixer'
  | 'sampleLayer'
> & {
  oscA?: Partial<OscillatorState>;
  oscB?: Partial<OscillatorState>;
  subOsc?: Partial<SubOscillatorState>;
  noise?: Partial<NoiseState>;
  filter?: Partial<FilterState>;
  ampEnv?: Partial<EnvelopeState>;
  filterEnv?: Partial<EnvelopeState>;
  lfo1?: Partial<LfoState>;
  lfo2?: Partial<LfoState>;
  waveSequencer?: Partial<WaveSequencerState>;
  vectorMixer?: Partial<VectorMixerState>;
  sampleLayer?: Partial<SampleLayerState>;
};

const createdAt = '2026-05-03T00:00:00.000Z';

export const presetCategoryOrder: PresetCategory[] = [
  'Bass',
  'Lead',
  'Pad',
  'Pluck',
  'Keys',
  'Piano',
  'E-Piano',
  'Organ',
  'Strings',
  'Choir',
  'Brass',
  'Woodwind',
  'Guitar',
  'Bell',
  'Mallet',
  'Drum',
  'Sequence',
  'Ambient',
  'FX',
  'Experimental',
];

function engine(overrides: EngineOverrides): SynthEngineState {
  const defaults = createDefaultEngineState();
  return {
    ...defaults,
    ...overrides,
    oscA: { ...defaults.oscA, ...overrides.oscA },
    oscB: { ...defaults.oscB, ...overrides.oscB },
    subOsc: { ...defaults.subOsc, ...overrides.subOsc },
    noise: { ...defaults.noise, ...overrides.noise },
    filter: { ...defaults.filter, ...overrides.filter },
    ampEnv: { ...defaults.ampEnv, ...overrides.ampEnv },
    filterEnv: { ...defaults.filterEnv, ...overrides.filterEnv },
    lfo1: { ...defaults.lfo1, ...overrides.lfo1 },
    lfo2: { ...defaults.lfo2, ...overrides.lfo2 },
    waveSequencer: { ...defaults.waveSequencer, ...overrides.waveSequencer },
    vectorMixer: { ...defaults.vectorMixer, ...overrides.vectorMixer },
    sampleLayer: { ...defaults.sampleLayer, ...overrides.sampleLayer },
    effects: overrides.effects ?? defaults.effects,
  };
}

function preset(id: string, name: string, category: PresetCategory, overrides: EngineOverrides): SynthPreset {
  return {
    id: `factory-${id}`,
    name,
    category,
    author: 'Factory',
    createdAt,
    engine: engine(overrides),
  };
}

function fx(id: string, type: EffectType, wet: number, params: Record<string, number> = {}): EffectState {
  return {
    id: `preset-fx-${id}`,
    type,
    enabled: true,
    wet,
    params,
  };
}

export const factoryPresets: SynthPreset[] = [
  preset('analog-deep-bass', 'Analog Deep Bass', 'Bass', {
    oscA: { waveform: 'sawtooth', octave: -1, level: 0.88 },
    oscB: { waveform: 'square', octave: -1, fine: 3, level: 0.46 },
    subOsc: { enabled: true, waveform: 'sine', octave: -2, level: 0.38 },
    filter: { type: 'ladder', cutoff: 720, resonance: 5.5, drive: 0.42, keyTracking: 0.18, envelopeAmount: 0.34 },
    ampEnv: { attack: 0.006, decay: 0.14, sustain: 0.82, release: 0.16 },
    filterEnv: { attack: 0.004, decay: 0.24, sustain: 0.24, release: 0.12 },
    vectorMixer: { x: 0.32, y: 0.12 },
  }),
  preset('prophet-round-bass', 'Prophet Round Bass', 'Bass', {
    oscA: { waveform: 'sawtooth', octave: -1, fine: -2, level: 0.82 },
    oscB: { waveform: 'triangle', octave: -1, fine: 5, level: 0.54 },
    subOsc: { enabled: true, waveform: 'square', octave: -2, level: 0.28 },
    filter: { type: 'ladder', cutoff: 980, resonance: 2.8, drive: 0.24, keyTracking: 0.2, envelopeAmount: 0.22 },
    ampEnv: { attack: 0.008, decay: 0.2, sustain: 0.72, release: 0.22 },
    filterEnv: { attack: 0.006, decay: 0.3, sustain: 0.28, release: 0.18 },
    vectorMixer: { x: 0.38, y: 0.16 },
  }),
  preset('rubber-pulse-bass', 'Rubber Pulse Bass', 'Bass', {
    oscA: { waveform: 'pulse', octave: -1, fine: -5, level: 0.86 },
    oscB: { waveform: 'square', octave: -1, semitone: 0, fine: 8, level: 0.62 },
    subOsc: { enabled: true, waveform: 'sine', octave: -2, level: 0.3 },
    filter: { type: 'lowpass', cutoff: 620, resonance: 8.4, drive: 0.34, keyTracking: 0.24, envelopeAmount: 0.42 },
    ampEnv: { attack: 0.004, decay: 0.18, sustain: 0.54, release: 0.14 },
    filterEnv: { attack: 0.002, decay: 0.22, sustain: 0.12, release: 0.12 },
    vectorMixer: { x: 0.54, y: 0.14 },
  }),
  preset('sub-foundation', 'Sub Foundation', 'Bass', {
    oscA: { waveform: 'sine', octave: -1, level: 0.54 },
    oscB: { waveform: 'triangle', octave: -1, fine: -4, level: 0.34 },
    subOsc: { enabled: true, waveform: 'sine', octave: -2, level: 0.72 },
    filter: { type: 'lowpass', cutoff: 420, resonance: 1.2, drive: 0.12, keyTracking: 0.1, envelopeAmount: 0.08 },
    ampEnv: { attack: 0.012, decay: 0.16, sustain: 0.94, release: 0.24 },
    filterEnv: { attack: 0.012, decay: 0.18, sustain: 0.62, release: 0.18 },
    vectorMixer: { x: 0.18, y: 0.52 },
  }),
  preset('acid-ladder-bite', 'Acid Ladder Bite', 'Bass', {
    oscA: { waveform: 'sawtooth', octave: -1, level: 0.78 },
    oscB: { waveform: 'pulse', octave: -1, fine: 11, level: 0.4 },
    subOsc: { enabled: false, level: 0 },
    filter: { type: 'ladder', cutoff: 880, resonance: 14.8, drive: 0.52, keyTracking: 0.18, envelopeAmount: 0.62 },
    ampEnv: { attack: 0.002, decay: 0.12, sustain: 0.38, release: 0.08 },
    filterEnv: { attack: 0.001, decay: 0.16, sustain: 0.08, release: 0.08 },
    vectorMixer: { x: 0.42, y: 0 },
  }),
  preset('dark-reese-stack', 'Dark Reese Stack', 'Bass', {
    oscA: { waveform: 'sawtooth', octave: -1, fine: -14, level: 0.78 },
    oscB: { waveform: 'sawtooth', octave: -1, fine: 14, level: 0.78 },
    subOsc: { enabled: true, waveform: 'square', octave: -2, level: 0.2 },
    noise: { enabled: true, kind: 'pink', level: 0.03 },
    filter: { type: 'lowpass', cutoff: 1450, resonance: 2.4, drive: 0.36, keyTracking: 0.18, envelopeAmount: 0.12 },
    ampEnv: { attack: 0.018, decay: 0.32, sustain: 0.8, release: 0.34 },
    filterEnv: { attack: 0.02, decay: 0.42, sustain: 0.5, release: 0.28 },
    vectorMixer: { x: 0.5, y: 0.12 },
  }),

  preset('bright-saw-lead', 'Bright Saw Lead', 'Lead', {
    oscA: { waveform: 'sawtooth', octave: 0, fine: -4, level: 0.78 },
    oscB: { waveform: 'sawtooth', octave: 0, semitone: 7, fine: 5, level: 0.64 },
    subOsc: { enabled: false, level: 0 },
    filter: { type: 'lowpass', cutoff: 4200, resonance: 3.4, drive: 0.16, keyTracking: 0.36, envelopeAmount: 0.12 },
    ampEnv: { attack: 0.01, decay: 0.08, sustain: 0.68, release: 0.24 },
    filterEnv: { attack: 0.01, decay: 0.12, sustain: 0.58, release: 0.18 },
    vectorMixer: { x: 0.52, y: 0 },
  }),
  preset('fifth-prophet-lead', 'Fifth Prophet Lead', 'Lead', {
    oscA: { waveform: 'sawtooth', octave: 0, fine: -7, level: 0.76 },
    oscB: { waveform: 'pulse', octave: 0, semitone: 7, fine: 7, level: 0.66 },
    subOsc: { enabled: false, level: 0 },
    filter: { type: 'ladder', cutoff: 3600, resonance: 4.8, drive: 0.18, keyTracking: 0.42, envelopeAmount: 0.16 },
    ampEnv: { attack: 0.008, decay: 0.12, sustain: 0.7, release: 0.28 },
    filterEnv: { attack: 0.006, decay: 0.18, sustain: 0.48, release: 0.2 },
    vectorMixer: { x: 0.56, y: 0 },
  }),
  preset('square-solo-voice', 'Square Solo Voice', 'Lead', {
    oscA: { waveform: 'square', octave: 0, level: 0.8 },
    oscB: { waveform: 'pulse', octave: 0, fine: -9, level: 0.52 },
    subOsc: { enabled: true, waveform: 'triangle', octave: -1, level: 0.12 },
    filter: { type: 'lowpass', cutoff: 3000, resonance: 5.2, drive: 0.12, keyTracking: 0.52, envelopeAmount: 0.08 },
    ampEnv: { attack: 0.012, decay: 0.1, sustain: 0.76, release: 0.3 },
    filterEnv: { attack: 0.01, decay: 0.12, sustain: 0.58, release: 0.2 },
    vectorMixer: { x: 0.4, y: 0.08 },
  }),
  preset('reed-cut-lead', 'Reed Cut Lead', 'Lead', {
    oscA: { waveform: 'pulse', octave: 0, fine: -3, level: 0.74 },
    oscB: { waveform: 'triangle', octave: 1, fine: 2, level: 0.38 },
    subOsc: { enabled: false, level: 0 },
    filter: { type: 'bandpass', cutoff: 2400, resonance: 8.8, drive: 0.14, keyTracking: 0.48, envelopeAmount: 0.2 },
    ampEnv: { attack: 0.006, decay: 0.1, sustain: 0.64, release: 0.16 },
    filterEnv: { attack: 0.004, decay: 0.18, sustain: 0.28, release: 0.12 },
    vectorMixer: { x: 0.32, y: 0.02 },
  }),
  preset('glass-wavetable-lead', 'Glass Wavetable Lead', 'Lead', {
    oscA: { waveform: 'wavetable', octave: 0, fine: -6, level: 0.7 },
    oscB: { waveform: 'sine', octave: 1, semitone: 0, fine: 6, level: 0.48 },
    subOsc: { enabled: false, level: 0 },
    filter: { type: 'highpass', cutoff: 1300, resonance: 3.4, drive: 0.04, keyTracking: 0.28, envelopeAmount: 0.04 },
    ampEnv: { attack: 0.012, decay: 0.16, sustain: 0.72, release: 0.38 },
    filterEnv: { attack: 0.012, decay: 0.2, sustain: 0.52, release: 0.22 },
    vectorMixer: { x: 0.46, y: 0 },
  }),
  preset('thin-wire-lead', 'Thin Wire Lead', 'Lead', {
    oscA: { waveform: 'triangle', octave: 1, fine: -5, level: 0.62 },
    oscB: { waveform: 'pulse', octave: 1, semitone: -12, fine: 5, level: 0.5 },
    subOsc: { enabled: false, level: 0 },
    filter: { type: 'notch', cutoff: 3300, resonance: 10.4, drive: 0.08, keyTracking: 0.32, envelopeAmount: -0.08 },
    ampEnv: { attack: 0.006, decay: 0.08, sustain: 0.58, release: 0.18 },
    filterEnv: { attack: 0.004, decay: 0.16, sustain: 0.4, release: 0.12 },
    vectorMixer: { x: 0.58, y: 0 },
  }),

  preset('warm-vector-pad', 'Warm Vector Pad', 'Pad', {
    oscA: { waveform: 'triangle', octave: 0, fine: -8, level: 0.7 },
    oscB: { waveform: 'wavetable', octave: 0, semitone: 12, fine: 8, level: 0.58 },
    subOsc: { enabled: true, waveform: 'sine', octave: -1, level: 0.14 },
    noise: { enabled: true, kind: 'pink', level: 0.08 },
    filter: { type: 'lowpass', cutoff: 2600, resonance: 1.2, drive: 0.08, keyTracking: 0.12, envelopeAmount: 0.08 },
    ampEnv: { attack: 0.72, decay: 1.1, sustain: 0.74, release: 1.6 },
    filterEnv: { attack: 1.1, decay: 1.4, sustain: 0.5, release: 1.2 },
    vectorMixer: { x: 0.44, y: 0.28 },
  }),
  preset('vintage-brass-pad', 'Vintage Brass Pad', 'Pad', {
    oscA: { waveform: 'sawtooth', octave: 0, fine: -6, level: 0.78 },
    oscB: { waveform: 'sawtooth', octave: 0, fine: 7, level: 0.72 },
    subOsc: { enabled: true, waveform: 'triangle', octave: -1, level: 0.16 },
    filter: { type: 'ladder', cutoff: 1800, resonance: 2.6, drive: 0.14, keyTracking: 0.18, envelopeAmount: 0.24 },
    ampEnv: { attack: 0.42, decay: 0.9, sustain: 0.84, release: 1.25 },
    filterEnv: { attack: 0.38, decay: 0.9, sustain: 0.46, release: 0.9 },
    vectorMixer: { x: 0.48, y: 0.12 },
  }),
  preset('tape-string-pad', 'Tape String Pad', 'Pad', {
    oscA: { waveform: 'triangle', octave: 0, fine: -12, level: 0.76 },
    oscB: { waveform: 'sawtooth', octave: 0, fine: 12, level: 0.46 },
    subOsc: { enabled: true, waveform: 'sine', octave: -1, level: 0.1 },
    noise: { enabled: true, kind: 'pink', level: 0.04 },
    filter: { type: 'lowpass', cutoff: 2100, resonance: 1.4, drive: 0.06, keyTracking: 0.14, envelopeAmount: 0.06 },
    ampEnv: { attack: 0.9, decay: 1.4, sustain: 0.72, release: 1.7 },
    filterEnv: { attack: 1.2, decay: 1.4, sustain: 0.52, release: 1.4 },
    vectorMixer: { x: 0.36, y: 0.16 },
  }),
  preset('velvet-choir-pad', 'Velvet Choir Pad', 'Pad', {
    oscA: { waveform: 'wavetable', octave: 0, fine: -3, level: 0.64 },
    oscB: { waveform: 'triangle', octave: 0, semitone: 7, fine: 3, level: 0.58 },
    subOsc: { enabled: true, waveform: 'sine', octave: -1, level: 0.08 },
    filter: { type: 'bandpass', cutoff: 1700, resonance: 3.2, drive: 0.04, keyTracking: 0.08, envelopeAmount: 0.02 },
    ampEnv: { attack: 1.1, decay: 1.6, sustain: 0.76, release: 2.1 },
    filterEnv: { attack: 1.3, decay: 1.7, sustain: 0.54, release: 1.8 },
    vectorMixer: { x: 0.42, y: 0.2 },
  }),
  preset('cloud-pwm-pad', 'Cloud PWM Pad', 'Pad', {
    oscA: { waveform: 'pulse', octave: 0, fine: -10, level: 0.7 },
    oscB: { waveform: 'pulse', octave: 0, fine: 10, level: 0.7 },
    subOsc: { enabled: false, level: 0 },
    noise: { enabled: true, kind: 'pink', level: 0.06 },
    filter: { type: 'notch', cutoff: 2200, resonance: 6.2, drive: 0.06, keyTracking: 0.12, envelopeAmount: -0.05 },
    ampEnv: { attack: 0.68, decay: 1.2, sustain: 0.7, release: 1.8 },
    filterEnv: { attack: 1.2, decay: 1.5, sustain: 0.48, release: 1.2 },
    vectorMixer: { x: 0.5, y: 0.04 },
  }),
  preset('soft-organ-pad', 'Soft Organ Pad', 'Pad', {
    oscA: { waveform: 'sine', octave: 0, level: 0.58 },
    oscB: { waveform: 'triangle', octave: 1, semitone: 0, fine: 1, level: 0.42 },
    subOsc: { enabled: true, waveform: 'sine', octave: -1, level: 0.12 },
    filter: { type: 'lowpass', cutoff: 5200, resonance: 0.8, drive: 0.02, keyTracking: 0.2, envelopeAmount: 0.02 },
    ampEnv: { attack: 0.18, decay: 0.45, sustain: 0.92, release: 0.78 },
    filterEnv: { attack: 0.18, decay: 0.5, sustain: 0.8, release: 0.5 },
    vectorMixer: { x: 0.28, y: 0.22 },
  }),

  preset('short-digital-pluck', 'Short Digital Pluck', 'Pluck', {
    oscA: { waveform: 'pulse', octave: 0, level: 0.72 },
    oscB: { waveform: 'wavetable', octave: 1, level: 0.46 },
    subOsc: { enabled: false, level: 0 },
    filter: { type: 'bandpass', cutoff: 3200, resonance: 7.8, drive: 0.1, keyTracking: 0.22, envelopeAmount: 0.32 },
    ampEnv: { attack: 0.002, decay: 0.22, sustain: 0.04, release: 0.18 },
    filterEnv: { attack: 0.002, decay: 0.18, sustain: 0.08, release: 0.14 },
    vectorMixer: { x: 0.42, y: 0 },
  }),
  preset('wooden-reso-pluck', 'Wooden Reso Pluck', 'Pluck', {
    oscA: { waveform: 'triangle', octave: 0, level: 0.68 },
    oscB: { waveform: 'pulse', octave: 0, semitone: 12, fine: -4, level: 0.36 },
    subOsc: { enabled: false, level: 0 },
    filter: { type: 'bandpass', cutoff: 1200, resonance: 11.2, drive: 0.08, keyTracking: 0.36, envelopeAmount: 0.28 },
    ampEnv: { attack: 0.001, decay: 0.16, sustain: 0.02, release: 0.12 },
    filterEnv: { attack: 0.001, decay: 0.16, sustain: 0.04, release: 0.1 },
    vectorMixer: { x: 0.34, y: 0 },
  }),
  preset('harp-pop', 'Harp Pop', 'Pluck', {
    oscA: { waveform: 'sine', octave: 0, level: 0.58 },
    oscB: { waveform: 'triangle', octave: 1, fine: 2, level: 0.5 },
    subOsc: { enabled: false, level: 0 },
    filter: { type: 'highpass', cutoff: 780, resonance: 2.2, drive: 0.02, keyTracking: 0.28, envelopeAmount: 0.08 },
    ampEnv: { attack: 0.002, decay: 0.44, sustain: 0.06, release: 0.32 },
    filterEnv: { attack: 0.002, decay: 0.38, sustain: 0.12, release: 0.28 },
    vectorMixer: { x: 0.46, y: 0 },
  }),
  preset('muted-pizzicato', 'Muted Pizzicato', 'Pluck', {
    oscA: { waveform: 'square', octave: 0, fine: -3, level: 0.5 },
    oscB: { waveform: 'triangle', octave: 0, semitone: 7, fine: 3, level: 0.42 },
    subOsc: { enabled: false, level: 0 },
    filter: { type: 'lowpass', cutoff: 980, resonance: 5.8, drive: 0.04, keyTracking: 0.2, envelopeAmount: 0.16 },
    ampEnv: { attack: 0.001, decay: 0.18, sustain: 0.02, release: 0.08 },
    filterEnv: { attack: 0.001, decay: 0.14, sustain: 0.06, release: 0.08 },
    vectorMixer: { x: 0.48, y: 0 },
  }),
  preset('octave-click-pluck', 'Octave Click Pluck', 'Pluck', {
    oscA: { waveform: 'pulse', octave: 0, level: 0.56 },
    oscB: { waveform: 'sawtooth', octave: 1, fine: 1, level: 0.34 },
    subOsc: { enabled: false, level: 0 },
    filter: { type: 'notch', cutoff: 2800, resonance: 8.4, drive: 0.08, keyTracking: 0.26, envelopeAmount: 0.18 },
    ampEnv: { attack: 0.001, decay: 0.12, sustain: 0.01, release: 0.08 },
    filterEnv: { attack: 0.001, decay: 0.12, sustain: 0.04, release: 0.08 },
    vectorMixer: { x: 0.44, y: 0 },
  }),
  preset('soft-key-pluck', 'Soft Key Pluck', 'Pluck', {
    oscA: { waveform: 'triangle', octave: 0, fine: -2, level: 0.62 },
    oscB: { waveform: 'wavetable', octave: 0, semitone: 12, fine: 2, level: 0.36 },
    subOsc: { enabled: false, level: 0 },
    filter: { type: 'lowpass', cutoff: 2400, resonance: 2.8, drive: 0.03, keyTracking: 0.28, envelopeAmount: 0.12 },
    ampEnv: { attack: 0.006, decay: 0.36, sustain: 0.12, release: 0.28 },
    filterEnv: { attack: 0.006, decay: 0.34, sustain: 0.22, release: 0.22 },
    vectorMixer: { x: 0.42, y: 0 },
  }),

  preset('ice-bell', 'Ice Bell', 'Bell', {
    oscA: { waveform: 'sine', octave: 1, level: 0.54 },
    oscB: { waveform: 'wavetable', octave: 1, semitone: 7, fine: 4, level: 0.48 },
    subOsc: { enabled: false, level: 0 },
    filter: { type: 'highpass', cutoff: 1300, resonance: 4.2, drive: 0.02, keyTracking: 0.24, envelopeAmount: 0.08 },
    ampEnv: { attack: 0.004, decay: 1.1, sustain: 0.02, release: 1.2 },
    filterEnv: { attack: 0.004, decay: 0.8, sustain: 0.04, release: 0.9 },
    vectorMixer: { x: 0.52, y: 0 },
  }),
  preset('tubular-digital-bell', 'Tubular Digital Bell', 'Bell', {
    oscA: { waveform: 'sine', octave: 0, level: 0.46 },
    oscB: { waveform: 'triangle', octave: 1, semitone: 5, fine: -2, level: 0.58 },
    subOsc: { enabled: false, level: 0 },
    filter: { type: 'bandpass', cutoff: 1800, resonance: 6.4, drive: 0.04, keyTracking: 0.16, envelopeAmount: 0.12 },
    ampEnv: { attack: 0.004, decay: 1.35, sustain: 0.04, release: 1.4 },
    filterEnv: { attack: 0.004, decay: 0.9, sustain: 0.08, release: 0.9 },
    vectorMixer: { x: 0.62, y: 0 },
  }),
  preset('celeste-glass', 'Celeste Glass', 'Bell', {
    oscA: { waveform: 'triangle', octave: 1, fine: -4, level: 0.46 },
    oscB: { waveform: 'wavetable', octave: 2, semitone: 0, fine: 4, level: 0.36 },
    subOsc: { enabled: false, level: 0 },
    filter: { type: 'highpass', cutoff: 1900, resonance: 2.8, drive: 0.02, keyTracking: 0.24, envelopeAmount: 0.04 },
    ampEnv: { attack: 0.006, decay: 0.9, sustain: 0.06, release: 1.0 },
    filterEnv: { attack: 0.006, decay: 0.7, sustain: 0.08, release: 0.72 },
    vectorMixer: { x: 0.46, y: 0 },
  }),
  preset('toy-music-box', 'Toy Music Box', 'Bell', {
    oscA: { waveform: 'pulse', octave: 1, level: 0.38 },
    oscB: { waveform: 'sine', octave: 2, semitone: 0, fine: 0, level: 0.34 },
    subOsc: { enabled: false, level: 0 },
    filter: { type: 'bandpass', cutoff: 2600, resonance: 9.2, drive: 0.02, keyTracking: 0.2, envelopeAmount: 0.1 },
    ampEnv: { attack: 0.002, decay: 0.72, sustain: 0.02, release: 0.86 },
    filterEnv: { attack: 0.002, decay: 0.42, sustain: 0.06, release: 0.42 },
    vectorMixer: { x: 0.48, y: 0 },
  }),
  preset('soft-chime', 'Soft Chime', 'Bell', {
    oscA: { waveform: 'sine', octave: 1, fine: -1, level: 0.48 },
    oscB: { waveform: 'triangle', octave: 1, semitone: 12, fine: 1, level: 0.28 },
    subOsc: { enabled: false, level: 0 },
    filter: { type: 'lowpass', cutoff: 5400, resonance: 1.8, drive: 0.01, keyTracking: 0.2, envelopeAmount: 0.02 },
    ampEnv: { attack: 0.02, decay: 1.2, sustain: 0.08, release: 1.4 },
    filterEnv: { attack: 0.02, decay: 1.0, sustain: 0.22, release: 0.9 },
    vectorMixer: { x: 0.36, y: 0 },
  }),
  preset('metallic-glock', 'Metallic Glock', 'Bell', {
    oscA: { waveform: 'wavetable', octave: 1, fine: -8, level: 0.52 },
    oscB: { waveform: 'sine', octave: 2, semitone: -5, fine: 8, level: 0.3 },
    subOsc: { enabled: false, level: 0 },
    filter: { type: 'notch', cutoff: 3300, resonance: 12.4, drive: 0.03, keyTracking: 0.18, envelopeAmount: 0.06 },
    ampEnv: { attack: 0.002, decay: 0.82, sustain: 0.03, release: 0.9 },
    filterEnv: { attack: 0.002, decay: 0.54, sustain: 0.08, release: 0.54 },
    vectorMixer: { x: 0.56, y: 0 },
  }),

  preset('pulse-stepper', 'Pulse Stepper', 'Sequence', {
    bpm: 124,
    oscA: { waveform: 'pulse', octave: 0, level: 0.76 },
    oscB: { waveform: 'square', octave: 0, semitone: 12, fine: -3, level: 0.34 },
    subOsc: { enabled: true, waveform: 'square', octave: -1, level: 0.12 },
    filter: { type: 'ladder', cutoff: 1450, resonance: 6.2, drive: 0.2, keyTracking: 0.22, envelopeAmount: 0.38 },
    ampEnv: { attack: 0.002, decay: 0.16, sustain: 0.18, release: 0.1 },
    filterEnv: { attack: 0.002, decay: 0.18, sustain: 0.1, release: 0.1 },
    waveSequencer: { enabled: true, tempoSync: true },
    vectorMixer: { x: 0.42, y: 0.08 },
  }),
  preset('fifth-sequence-key', 'Fifth Sequence Key', 'Sequence', {
    bpm: 132,
    oscA: { waveform: 'sawtooth', octave: 0, level: 0.72 },
    oscB: { waveform: 'pulse', octave: 0, semitone: 7, fine: 2, level: 0.48 },
    subOsc: { enabled: false, level: 0 },
    filter: { type: 'bandpass', cutoff: 2100, resonance: 7.8, drive: 0.12, keyTracking: 0.28, envelopeAmount: 0.28 },
    ampEnv: { attack: 0.002, decay: 0.18, sustain: 0.12, release: 0.12 },
    filterEnv: { attack: 0.002, decay: 0.18, sustain: 0.08, release: 0.12 },
    waveSequencer: { enabled: true, tempoSync: true },
    vectorMixer: { x: 0.52, y: 0 },
  }),
  preset('retro-comp-line', 'Retro Comp Line', 'Sequence', {
    bpm: 118,
    oscA: { waveform: 'square', octave: 0, fine: -4, level: 0.62 },
    oscB: { waveform: 'triangle', octave: 0, fine: 4, level: 0.44 },
    subOsc: { enabled: true, waveform: 'sine', octave: -1, level: 0.18 },
    filter: { type: 'lowpass', cutoff: 1600, resonance: 4.4, drive: 0.1, keyTracking: 0.2, envelopeAmount: 0.18 },
    ampEnv: { attack: 0.004, decay: 0.2, sustain: 0.28, release: 0.12 },
    filterEnv: { attack: 0.004, decay: 0.22, sustain: 0.18, release: 0.12 },
    waveSequencer: { enabled: true, tempoSync: true },
    vectorMixer: { x: 0.34, y: 0.14 },
  }),
  preset('glass-runner', 'Glass Runner', 'Sequence', {
    bpm: 140,
    oscA: { waveform: 'wavetable', octave: 0, fine: -6, level: 0.62 },
    oscB: { waveform: 'triangle', octave: 1, fine: 6, level: 0.42 },
    subOsc: { enabled: false, level: 0 },
    filter: { type: 'highpass', cutoff: 1200, resonance: 4.8, drive: 0.04, keyTracking: 0.2, envelopeAmount: 0.14 },
    ampEnv: { attack: 0.002, decay: 0.2, sustain: 0.08, release: 0.18 },
    filterEnv: { attack: 0.002, decay: 0.2, sustain: 0.12, release: 0.14 },
    waveSequencer: { enabled: true, tempoSync: true },
    vectorMixer: { x: 0.5, y: 0 },
  }),
  preset('sub-step-pulse', 'Sub Step Pulse', 'Sequence', {
    bpm: 112,
    oscA: { waveform: 'pulse', octave: -1, level: 0.64 },
    oscB: { waveform: 'sawtooth', octave: -1, fine: 5, level: 0.34 },
    subOsc: { enabled: true, waveform: 'square', octave: -2, level: 0.34 },
    filter: { type: 'ladder', cutoff: 760, resonance: 7.6, drive: 0.24, keyTracking: 0.16, envelopeAmount: 0.34 },
    ampEnv: { attack: 0.002, decay: 0.12, sustain: 0.22, release: 0.08 },
    filterEnv: { attack: 0.002, decay: 0.16, sustain: 0.08, release: 0.08 },
    waveSequencer: { enabled: true, tempoSync: true },
    vectorMixer: { x: 0.3, y: 0.24 },
  }),
  preset('notch-motion-seq', 'Notch Motion Seq', 'Sequence', {
    bpm: 126,
    oscA: { waveform: 'sawtooth', octave: 0, fine: -9, level: 0.66 },
    oscB: { waveform: 'pulse', octave: 0, fine: 9, level: 0.52 },
    noise: { enabled: true, kind: 'pink', level: 0.03 },
    filter: { type: 'notch', cutoff: 1800, resonance: 9.6, drive: 0.08, keyTracking: 0.16, envelopeAmount: -0.16 },
    ampEnv: { attack: 0.004, decay: 0.22, sustain: 0.18, release: 0.12 },
    filterEnv: { attack: 0.004, decay: 0.26, sustain: 0.12, release: 0.12 },
    waveSequencer: { enabled: true, tempoSync: true },
    vectorMixer: { x: 0.48, y: 0.04 },
  }),

  preset('frozen-air', 'Frozen Air', 'Ambient', {
    oscA: { waveform: 'sine', octave: 0, fine: -11, level: 0.5 },
    oscB: { waveform: 'wavetable', octave: 1, semitone: 5, fine: 11, level: 0.62 },
    subOsc: { enabled: true, waveform: 'triangle', octave: -1, level: 0.08 },
    noise: { enabled: true, kind: 'pink', level: 0.12 },
    filter: { type: 'notch', cutoff: 1900, resonance: 9.2, drive: 0.04, keyTracking: 0.08, envelopeAmount: -0.08 },
    ampEnv: { attack: 1.2, decay: 2.2, sustain: 0.64, release: 2.4 },
    filterEnv: { attack: 1.8, decay: 2.4, sustain: 0.5, release: 1.8 },
    vectorMixer: { x: 0.62, y: 0.2 },
  }),
  preset('dusk-drone', 'Dusk Drone', 'Ambient', {
    oscA: { waveform: 'triangle', octave: -1, fine: -6, level: 0.58 },
    oscB: { waveform: 'sawtooth', octave: 0, fine: 6, level: 0.34 },
    subOsc: { enabled: true, waveform: 'sine', octave: -2, level: 0.18 },
    noise: { enabled: true, kind: 'pink', level: 0.08 },
    filter: { type: 'lowpass', cutoff: 1400, resonance: 1.8, drive: 0.04, keyTracking: 0.08, envelopeAmount: 0.02 },
    ampEnv: { attack: 1.8, decay: 2.4, sustain: 0.76, release: 3.2 },
    filterEnv: { attack: 2.2, decay: 2.8, sustain: 0.56, release: 2.8 },
    vectorMixer: { x: 0.3, y: 0.24 },
  }),
  preset('oceanic-noise-pad', 'Oceanic Noise Pad', 'Ambient', {
    oscA: { waveform: 'sine', octave: 0, level: 0.32 },
    oscB: { waveform: 'triangle', octave: 0, semitone: 7, level: 0.26 },
    subOsc: { enabled: false, level: 0 },
    noise: { enabled: true, kind: 'pink', level: 0.28 },
    filter: { type: 'bandpass', cutoff: 1100, resonance: 2.8, drive: 0.02, keyTracking: 0.04, envelopeAmount: 0.04 },
    ampEnv: { attack: 1.4, decay: 2.0, sustain: 0.68, release: 2.8 },
    filterEnv: { attack: 2.0, decay: 2.4, sustain: 0.5, release: 2.4 },
    vectorMixer: { x: 0.52, y: 0.52 },
  }),
  preset('ghost-choir', 'Ghost Choir', 'Ambient', {
    oscA: { waveform: 'wavetable', octave: 0, fine: -5, level: 0.5 },
    oscB: { waveform: 'triangle', octave: 1, semitone: -5, fine: 5, level: 0.42 },
    subOsc: { enabled: true, waveform: 'sine', octave: -1, level: 0.08 },
    filter: { type: 'bandpass', cutoff: 1500, resonance: 5.4, drive: 0.02, keyTracking: 0.1, envelopeAmount: 0.02 },
    ampEnv: { attack: 1.3, decay: 1.9, sustain: 0.7, release: 2.4 },
    filterEnv: { attack: 1.8, decay: 2.0, sustain: 0.48, release: 1.8 },
    vectorMixer: { x: 0.42, y: 0.18 },
  }),
  preset('deep-space-organ', 'Deep Space Organ', 'Ambient', {
    oscA: { waveform: 'sine', octave: -1, level: 0.46 },
    oscB: { waveform: 'triangle', octave: 0, semitone: 12, fine: 1, level: 0.42 },
    subOsc: { enabled: true, waveform: 'sine', octave: -2, level: 0.12 },
    filter: { type: 'lowpass', cutoff: 3600, resonance: 0.8, drive: 0.02, keyTracking: 0.12, envelopeAmount: 0.02 },
    ampEnv: { attack: 0.8, decay: 1.2, sustain: 0.86, release: 2.2 },
    filterEnv: { attack: 1.0, decay: 1.4, sustain: 0.72, release: 1.6 },
    vectorMixer: { x: 0.38, y: 0.22 },
  }),
  preset('sunrise-wash', 'Sunrise Wash', 'Ambient', {
    oscA: { waveform: 'sawtooth', octave: 0, fine: -9, level: 0.44 },
    oscB: { waveform: 'wavetable', octave: 1, semitone: 0, fine: 9, level: 0.5 },
    subOsc: { enabled: false, level: 0 },
    noise: { enabled: true, kind: 'pink', level: 0.1 },
    filter: { type: 'lowpass', cutoff: 2400, resonance: 1.4, drive: 0.03, keyTracking: 0.12, envelopeAmount: 0.14 },
    ampEnv: { attack: 2.2, decay: 2.4, sustain: 0.72, release: 3.0 },
    filterEnv: { attack: 2.4, decay: 2.6, sustain: 0.54, release: 2.2 },
    vectorMixer: { x: 0.56, y: 0.16 },
  }),

  preset('noise-sweep', 'Noise Sweep', 'FX', {
    oscA: { waveform: 'sine', octave: 0, level: 0.08 },
    oscB: { waveform: 'triangle', octave: 0, level: 0.04 },
    subOsc: { enabled: false, level: 0 },
    noise: { enabled: true, kind: 'white', level: 0.72 },
    filter: { type: 'lowpass', cutoff: 760, resonance: 8.2, drive: 0.04, keyTracking: 0.02, envelopeAmount: 0.86 },
    ampEnv: { attack: 0.04, decay: 1.2, sustain: 0.18, release: 1.4 },
    filterEnv: { attack: 0.7, decay: 1.6, sustain: 0.18, release: 1.2 },
    vectorMixer: { x: 0.9, y: 0.86 },
  }),
  preset('laser-zap', 'Laser Zap', 'FX', {
    oscA: { waveform: 'sawtooth', octave: 1, fine: 0, level: 0.62 },
    oscB: { waveform: 'square', octave: 0, semitone: -12, level: 0.42 },
    subOsc: { enabled: false, level: 0 },
    filter: { type: 'bandpass', cutoff: 6200, resonance: 16.0, drive: 0.18, keyTracking: 0.1, envelopeAmount: -0.7 },
    ampEnv: { attack: 0.001, decay: 0.28, sustain: 0.02, release: 0.18 },
    filterEnv: { attack: 0.001, decay: 0.22, sustain: 0.02, release: 0.14 },
    vectorMixer: { x: 0.42, y: 0 },
  }),
  preset('sub-drop', 'Sub Drop', 'FX', {
    oscA: { waveform: 'sine', octave: -1, level: 0.62 },
    oscB: { waveform: 'triangle', octave: -2, level: 0.38 },
    subOsc: { enabled: true, waveform: 'sine', octave: -2, level: 0.42 },
    filter: { type: 'lowpass', cutoff: 380, resonance: 1.2, drive: 0.18, keyTracking: 0.02, envelopeAmount: -0.08 },
    ampEnv: { attack: 0.004, decay: 1.4, sustain: 0.22, release: 1.2 },
    filterEnv: { attack: 0.004, decay: 1.0, sustain: 0.3, release: 1.0 },
    vectorMixer: { x: 0.22, y: 0.34 },
  }),
  preset('metal-hit', 'Metal Hit', 'FX', {
    oscA: { waveform: 'wavetable', octave: 0, fine: -22, level: 0.58 },
    oscB: { waveform: 'pulse', octave: 1, semitone: 6, fine: 19, level: 0.5 },
    noise: { enabled: true, kind: 'white', level: 0.18 },
    filter: { type: 'notch', cutoff: 2400, resonance: 18.2, drive: 0.22, keyTracking: 0.08, envelopeAmount: 0.16 },
    ampEnv: { attack: 0.001, decay: 0.42, sustain: 0.04, release: 0.44 },
    filterEnv: { attack: 0.001, decay: 0.32, sustain: 0.06, release: 0.28 },
    vectorMixer: { x: 0.54, y: 0.12 },
  }),
  preset('wind-tunnel', 'Wind Tunnel', 'FX', {
    oscA: { waveform: 'sine', octave: 0, level: 0.06 },
    oscB: { waveform: 'triangle', octave: 0, level: 0.04 },
    noise: { enabled: true, kind: 'pink', level: 0.68 },
    filter: { type: 'bandpass', cutoff: 740, resonance: 5.8, drive: 0.04, keyTracking: 0.02, envelopeAmount: 0.18 },
    ampEnv: { attack: 0.8, decay: 1.4, sustain: 0.66, release: 1.8 },
    filterEnv: { attack: 1.0, decay: 1.6, sustain: 0.48, release: 1.4 },
    vectorMixer: { x: 0.72, y: 0.86 },
  }),
  preset('data-burst', 'Data Burst', 'FX', {
    oscA: { waveform: 'pulse', octave: 1, fine: -18, level: 0.48 },
    oscB: { waveform: 'wavetable', octave: 2, semitone: -7, fine: 18, level: 0.44 },
    noise: { enabled: true, kind: 'white', level: 0.1 },
    filter: { type: 'highpass', cutoff: 2600, resonance: 11.6, drive: 0.08, keyTracking: 0.14, envelopeAmount: 0.22 },
    ampEnv: { attack: 0.001, decay: 0.16, sustain: 0.01, release: 0.12 },
    filterEnv: { attack: 0.001, decay: 0.14, sustain: 0.04, release: 0.08 },
    vectorMixer: { x: 0.58, y: 0.08 },
  }),

  preset('alias-dust', 'Alias Dust', 'Experimental', {
    oscA: { waveform: 'wavetable', octave: 1, fine: -31, level: 0.52 },
    oscB: { waveform: 'pulse', octave: 1, semitone: 5, fine: 29, level: 0.46 },
    noise: { enabled: true, kind: 'white', level: 0.08 },
    filter: { type: 'notch', cutoff: 4200, resonance: 17.5, drive: 0.12, keyTracking: 0.08, envelopeAmount: -0.18 },
    ampEnv: { attack: 0.003, decay: 0.34, sustain: 0.2, release: 0.24 },
    filterEnv: { attack: 0.003, decay: 0.28, sustain: 0.16, release: 0.2 },
    vectorMixer: { x: 0.48, y: 0.08 },
  }),
  preset('broken-radio', 'Broken Radio', 'Experimental', {
    oscA: { waveform: 'pulse', octave: 0, fine: -24, level: 0.4 },
    oscB: { waveform: 'wavetable', octave: 0, semitone: 11, fine: 18, level: 0.44 },
    noise: { enabled: true, kind: 'white', level: 0.24 },
    filter: { type: 'bandpass', cutoff: 1650, resonance: 12.8, drive: 0.18, keyTracking: 0.06, envelopeAmount: -0.06 },
    ampEnv: { attack: 0.004, decay: 0.28, sustain: 0.18, release: 0.22 },
    filterEnv: { attack: 0.004, decay: 0.22, sustain: 0.18, release: 0.16 },
    vectorMixer: { x: 0.54, y: 0.28 },
  }),
  preset('vector-clang', 'Vector Clang', 'Experimental', {
    oscA: { waveform: 'triangle', octave: 0, fine: -17, level: 0.52 },
    oscB: { waveform: 'wavetable', octave: 1, semitone: 6, fine: 23, level: 0.52 },
    subOsc: { enabled: true, waveform: 'square', octave: -1, level: 0.12 },
    noise: { enabled: true, kind: 'pink', level: 0.06 },
    filter: { type: 'notch', cutoff: 2800, resonance: 15.2, drive: 0.1, keyTracking: 0.1, envelopeAmount: 0.12 },
    ampEnv: { attack: 0.002, decay: 0.62, sustain: 0.08, release: 0.52 },
    filterEnv: { attack: 0.002, decay: 0.4, sustain: 0.08, release: 0.34 },
    vectorMixer: { x: 0.62, y: 0.16 },
  }),
  preset('formant-vowel', 'Formant Vowel', 'Experimental', {
    oscA: { waveform: 'wavetable', octave: 0, fine: -8, level: 0.54 },
    oscB: { waveform: 'pulse', octave: 0, semitone: 12, fine: 8, level: 0.36 },
    noise: { enabled: false, level: 0 },
    filter: { type: 'bandpass', cutoff: 980, resonance: 18.4, drive: 0.1, keyTracking: 0.12, envelopeAmount: 0.18 },
    ampEnv: { attack: 0.018, decay: 0.4, sustain: 0.5, release: 0.42 },
    filterEnv: { attack: 0.08, decay: 0.34, sustain: 0.24, release: 0.28 },
    vectorMixer: { x: 0.44, y: 0 },
  }),
  preset('thin-unstable', 'Thin Unstable', 'Experimental', {
    oscA: { waveform: 'pulse', octave: 1, fine: -43, level: 0.44 },
    oscB: { waveform: 'pulse', octave: 1, semitone: -1, fine: 41, level: 0.42 },
    subOsc: { enabled: false, level: 0 },
    filter: { type: 'highpass', cutoff: 2400, resonance: 7.8, drive: 0.06, keyTracking: 0.18, envelopeAmount: -0.1 },
    ampEnv: { attack: 0.006, decay: 0.26, sustain: 0.36, release: 0.22 },
    filterEnv: { attack: 0.004, decay: 0.22, sustain: 0.24, release: 0.16 },
    vectorMixer: { x: 0.5, y: 0 },
  }),
  preset('subharmonic-oddity', 'Subharmonic Oddity', 'Experimental', {
    oscA: { waveform: 'sine', octave: -1, fine: -5, level: 0.38 },
    oscB: { waveform: 'square', octave: 0, semitone: -7, fine: 5, level: 0.42 },
    subOsc: { enabled: true, waveform: 'triangle', octave: -2, level: 0.22 },
    noise: { enabled: true, kind: 'pink', level: 0.04 },
    filter: { type: 'ladder', cutoff: 720, resonance: 10.6, drive: 0.28, keyTracking: 0.06, envelopeAmount: 0.1 },
    ampEnv: { attack: 0.04, decay: 0.7, sustain: 0.42, release: 0.72 },
    filterEnv: { attack: 0.06, decay: 0.54, sustain: 0.26, release: 0.48 },
    vectorMixer: { x: 0.34, y: 0.28 },
  }),

  preset('minilab-rubber-sub', 'MiniLab Rubber Sub', 'Bass', {
    oscA: { waveform: 'square', octave: -1, fine: -6, level: 0.72 },
    oscB: { waveform: 'pulse', octave: -1, fine: 6, level: 0.46 },
    subOsc: { enabled: true, waveform: 'sine', octave: -2, level: 0.54 },
    filter: { type: 'ladder', cutoff: 520, resonance: 6.8, drive: 0.48, keyTracking: 0.12, envelopeAmount: 0.38 },
    ampEnv: { attack: 0.004, decay: 0.2, sustain: 0.74, release: 0.16 },
    filterEnv: { attack: 0.002, decay: 0.28, sustain: 0.16, release: 0.12 },
    lfo1: { waveform: 'triangle', rate: 0.18, depth: 0.08, target: 'filterCutoff', sync: 'free', syncValue: '1/4' },
    vectorMixer: { x: 0.26, y: 0.28 },
    effects: [fx('minilab-rubber-sub-compressor', 'compressor', 0.62, { threshold: -24, ratio: 5 })],
  }),
  preset('warehouse-hoover-bass', 'Warehouse Hoover Bass', 'Bass', {
    oscA: { waveform: 'sawtooth', octave: -1, fine: -21, level: 0.82 },
    oscB: { waveform: 'sawtooth', octave: -1, fine: 23, level: 0.78 },
    subOsc: { enabled: true, waveform: 'square', octave: -2, level: 0.24 },
    noise: { enabled: true, kind: 'pink', level: 0.04 },
    filter: { type: 'lowpass', cutoff: 1180, resonance: 3.8, drive: 0.42, keyTracking: 0.16, envelopeAmount: 0.18 },
    ampEnv: { attack: 0.01, decay: 0.3, sustain: 0.86, release: 0.34 },
    filterEnv: { attack: 0.006, decay: 0.34, sustain: 0.38, release: 0.24 },
    lfo1: { waveform: 'triangle', rate: 5.4, depth: 0.05, target: 'pitch', sync: 'free', syncValue: '1/8' },
    vectorMixer: { x: 0.5, y: 0.12 },
    effects: [fx('warehouse-hoover-bass-distortion', 'distortion', 0.22, { drive: 0.36 })],
  }),
  preset('deep-fm-bubble-bass', 'Deep FM Bubble Bass', 'Bass', {
    oscA: { waveform: 'sine', octave: -1, level: 0.58 },
    oscB: { waveform: 'wavetable', octave: -1, semitone: 12, fine: -3, level: 0.52 },
    subOsc: { enabled: true, waveform: 'sine', octave: -2, level: 0.34 },
    filter: { type: 'bandpass', cutoff: 740, resonance: 9.4, drive: 0.18, keyTracking: 0.18, envelopeAmount: 0.44 },
    ampEnv: { attack: 0.006, decay: 0.26, sustain: 0.48, release: 0.18 },
    filterEnv: { attack: 0.002, decay: 0.34, sustain: 0.1, release: 0.14 },
    vectorMixer: { x: 0.44, y: 0.2 },
    effects: [fx('deep-fm-bubble-bass-phaser', 'phaser', 0.18, { frequency: 520, q: 6 })],
  }),
  preset('pluck-bass-click', 'Pluck Bass Click', 'Bass', {
    oscA: { waveform: 'pulse', octave: -1, level: 0.72 },
    oscB: { waveform: 'triangle', octave: -1, semitone: 7, level: 0.38 },
    subOsc: { enabled: true, waveform: 'square', octave: -2, level: 0.3 },
    filter: { type: 'ladder', cutoff: 680, resonance: 11.6, drive: 0.34, keyTracking: 0.2, envelopeAmount: 0.58 },
    ampEnv: { attack: 0.001, decay: 0.18, sustain: 0.22, release: 0.09 },
    filterEnv: { attack: 0.001, decay: 0.2, sustain: 0.04, release: 0.08 },
    vectorMixer: { x: 0.36, y: 0.18 },
  }),
  preset('wide-pan-bass', 'Wide Pan Bass', 'Bass', {
    oscA: { waveform: 'sawtooth', octave: -1, fine: -8, level: 0.76 },
    oscB: { waveform: 'pulse', octave: -1, fine: 8, level: 0.56 },
    subOsc: { enabled: true, waveform: 'sine', octave: -2, level: 0.28 },
    filter: { type: 'lowpass', cutoff: 1350, resonance: 2.2, drive: 0.26, keyTracking: 0.2, envelopeAmount: 0.18 },
    ampEnv: { attack: 0.012, decay: 0.22, sustain: 0.76, release: 0.24 },
    filterEnv: { attack: 0.01, decay: 0.34, sustain: 0.42, release: 0.22 },
    lfo2: { waveform: 'sine', rate: 0.38, depth: 0.42, target: 'pan', sync: 'free', syncValue: '1/2' },
    vectorMixer: { x: 0.52, y: 0.18 },
  }),
  preset('clean-sine-808', 'Clean Sine 808', 'Bass', {
    oscA: { waveform: 'sine', octave: -1, level: 0.38 },
    oscB: { waveform: 'sine', octave: -2, fine: 1, level: 0.24 },
    subOsc: { enabled: true, waveform: 'sine', octave: -2, level: 0.74 },
    filter: { type: 'lowpass', cutoff: 320, resonance: 0.9, drive: 0.08, keyTracking: 0.06, envelopeAmount: -0.04 },
    ampEnv: { attack: 0.004, decay: 1.6, sustain: 0.18, release: 0.9 },
    filterEnv: { attack: 0.004, decay: 1.0, sustain: 0.28, release: 0.8 },
    vectorMixer: { x: 0.2, y: 0.62 },
    effects: [fx('clean-sine-808-compressor', 'compressor', 0.78, { threshold: -28, ratio: 7 })],
  }),

  preset('mono-sync-siren', 'Mono Sync Siren', 'Lead', {
    oscA: { waveform: 'sawtooth', octave: 0, fine: -4, level: 0.72 },
    oscB: { waveform: 'pulse', octave: 1, semitone: -5, fine: 4, level: 0.42 },
    subOsc: { enabled: false, level: 0 },
    filter: { type: 'bandpass', cutoff: 2800, resonance: 9.6, drive: 0.16, keyTracking: 0.32, envelopeAmount: 0.16 },
    ampEnv: { attack: 0.006, decay: 0.18, sustain: 0.72, release: 0.18 },
    filterEnv: { attack: 0.004, decay: 0.2, sustain: 0.38, release: 0.14 },
    lfo1: { waveform: 'sine', rate: 5.2, depth: 0.08, target: 'pitch', sync: 'free', syncValue: '1/8' },
    vectorMixer: { x: 0.44, y: 0 },
    effects: [fx('mono-sync-siren-delay', 'delay', 0.24, { time: 0.21, feedback: 0.24 })],
  }),
  preset('neon-porta-lead', 'Neon Porta Lead', 'Lead', {
    oscA: { waveform: 'triangle', octave: 1, fine: -2, level: 0.6 },
    oscB: { waveform: 'wavetable', octave: 1, semitone: -12, fine: 2, level: 0.56 },
    subOsc: { enabled: false, level: 0 },
    filter: { type: 'highpass', cutoff: 980, resonance: 2.8, drive: 0.08, keyTracking: 0.36, envelopeAmount: 0.06 },
    ampEnv: { attack: 0.018, decay: 0.16, sustain: 0.82, release: 0.34 },
    filterEnv: { attack: 0.016, decay: 0.22, sustain: 0.52, release: 0.24 },
    lfo2: { waveform: 'triangle', rate: 0.42, depth: 0.18, target: 'pan', sync: 'free', syncValue: '1/2' },
    vectorMixer: { x: 0.62, y: 0 },
    effects: [fx('neon-porta-lead-chorus', 'chorus', 0.28, { time: 0.024, feedback: 0.16 })],
  }),
  preset('chip-square-hero', 'Chip Square Hero', 'Lead', {
    oscA: { waveform: 'square', octave: 0, level: 0.78 },
    oscB: { waveform: 'square', octave: 1, semitone: 7, level: 0.34 },
    subOsc: { enabled: false, level: 0 },
    filter: { type: 'lowpass', cutoff: 7200, resonance: 1.6, drive: 0.06, keyTracking: 0.46, envelopeAmount: 0.02 },
    ampEnv: { attack: 0.001, decay: 0.08, sustain: 0.78, release: 0.08 },
    filterEnv: { attack: 0.001, decay: 0.1, sustain: 0.72, release: 0.08 },
    vectorMixer: { x: 0.28, y: 0 },
    effects: [fx('chip-square-hero-bitcrusher', 'bitcrusher', 0.18, { drive: 0.42 })],
  }),
  preset('slow-vibrato-flute', 'Slow Vibrato Flute', 'Lead', {
    oscA: { waveform: 'sine', octave: 1, level: 0.5 },
    oscB: { waveform: 'triangle', octave: 1, fine: 3, level: 0.44 },
    subOsc: { enabled: false, level: 0 },
    noise: { enabled: true, kind: 'pink', level: 0.03 },
    filter: { type: 'bandpass', cutoff: 1900, resonance: 4.8, drive: 0.02, keyTracking: 0.32, envelopeAmount: 0.08 },
    ampEnv: { attack: 0.08, decay: 0.22, sustain: 0.74, release: 0.38 },
    filterEnv: { attack: 0.08, decay: 0.34, sustain: 0.48, release: 0.28 },
    lfo1: { waveform: 'sine', rate: 5.8, depth: 0.035, target: 'pitch', sync: 'free', syncValue: '1/8' },
    vectorMixer: { x: 0.46, y: 0.04 },
  }),
  preset('acid-hook-lead', 'Acid Hook Lead', 'Lead', {
    oscA: { waveform: 'pulse', octave: 0, level: 0.7 },
    oscB: { waveform: 'sawtooth', octave: 0, fine: 7, level: 0.5 },
    subOsc: { enabled: false, level: 0 },
    filter: { type: 'ladder', cutoff: 1280, resonance: 15.6, drive: 0.38, keyTracking: 0.26, envelopeAmount: 0.52 },
    ampEnv: { attack: 0.002, decay: 0.14, sustain: 0.52, release: 0.12 },
    filterEnv: { attack: 0.002, decay: 0.18, sustain: 0.08, release: 0.08 },
    vectorMixer: { x: 0.52, y: 0 },
    effects: [fx('acid-hook-lead-delay', 'delay', 0.18, { time: 0.16, feedback: 0.22 })],
  }),
  preset('wavetable-aria', 'Wavetable Aria', 'Lead', {
    oscA: { waveform: 'wavetable', octave: 0, fine: -6, level: 0.66 },
    oscB: { waveform: 'sine', octave: 1, semitone: 7, fine: 6, level: 0.38 },
    subOsc: { enabled: false, level: 0 },
    filter: { type: 'notch', cutoff: 3100, resonance: 7.4, drive: 0.04, keyTracking: 0.32, envelopeAmount: -0.04 },
    ampEnv: { attack: 0.026, decay: 0.18, sustain: 0.76, release: 0.42 },
    filterEnv: { attack: 0.02, decay: 0.24, sustain: 0.5, release: 0.32 },
    lfo1: { waveform: 'triangle', rate: 0.26, depth: 0.28, target: 'oscMix', sync: 'free', syncValue: '1/2' },
    vectorMixer: { x: 0.58, y: 0 },
    effects: [fx('wavetable-aria-reverb', 'reverb', 0.22, { decay: 1.4 })],
  }),

  preset('cinematic-silk-pad', 'Cinematic Silk Pad', 'Pad', {
    oscA: { waveform: 'triangle', octave: 0, fine: -9, level: 0.62 },
    oscB: { waveform: 'wavetable', octave: 0, semitone: 7, fine: 9, level: 0.58 },
    subOsc: { enabled: true, waveform: 'sine', octave: -1, level: 0.1 },
    noise: { enabled: true, kind: 'pink', level: 0.06 },
    filter: { type: 'lowpass', cutoff: 2300, resonance: 1.2, drive: 0.04, keyTracking: 0.12, envelopeAmount: 0.08 },
    ampEnv: { attack: 1.4, decay: 1.8, sustain: 0.78, release: 2.8 },
    filterEnv: { attack: 1.7, decay: 2.0, sustain: 0.54, release: 2.0 },
    lfo1: { waveform: 'sine', rate: 0.12, depth: 0.2, target: 'oscMix', sync: 'free', syncValue: '1/1' },
    vectorMixer: { x: 0.42, y: 0.24 },
    effects: [fx('cinematic-silk-pad-reverb', 'reverb', 0.36, { decay: 2.4 })],
  }),
  preset('pink-juno-cloud', 'Pink Juno Cloud', 'Pad', {
    oscA: { waveform: 'sawtooth', octave: 0, fine: -7, level: 0.72 },
    oscB: { waveform: 'pulse', octave: 0, fine: 7, level: 0.66 },
    subOsc: { enabled: true, waveform: 'triangle', octave: -1, level: 0.12 },
    filter: { type: 'ladder', cutoff: 1700, resonance: 2.2, drive: 0.12, keyTracking: 0.18, envelopeAmount: 0.18 },
    ampEnv: { attack: 0.55, decay: 1.0, sustain: 0.86, release: 1.7 },
    filterEnv: { attack: 0.5, decay: 1.2, sustain: 0.46, release: 1.0 },
    lfo2: { waveform: 'sine', rate: 0.2, depth: 0.32, target: 'pan', sync: 'free', syncValue: '1/1' },
    vectorMixer: { x: 0.5, y: 0.1 },
    effects: [fx('pink-juno-cloud-chorus', 'chorus', 0.34, { time: 0.028, feedback: 0.12 })],
  }),
  preset('shimmer-string-pad', 'Shimmer String Pad', 'Pad', {
    oscA: { waveform: 'sawtooth', octave: 0, fine: -11, level: 0.64 },
    oscB: { waveform: 'triangle', octave: 1, fine: 11, level: 0.42 },
    subOsc: { enabled: false, level: 0 },
    noise: { enabled: true, kind: 'pink', level: 0.04 },
    filter: { type: 'highpass', cutoff: 620, resonance: 1.8, drive: 0.03, keyTracking: 0.16, envelopeAmount: 0.04 },
    ampEnv: { attack: 0.78, decay: 1.3, sustain: 0.76, release: 2.2 },
    filterEnv: { attack: 1.0, decay: 1.4, sustain: 0.62, release: 1.6 },
    vectorMixer: { x: 0.36, y: 0.08 },
    effects: [fx('shimmer-string-pad-reverb', 'reverb', 0.42, { decay: 3.2 }), fx('shimmer-string-pad-delay', 'delay', 0.14, { time: 0.42, feedback: 0.18 })],
  }),
  preset('analog-choir-bloom', 'Analog Choir Bloom', 'Pad', {
    oscA: { waveform: 'wavetable', octave: 0, fine: -4, level: 0.58 },
    oscB: { waveform: 'wavetable', octave: 0, semitone: 12, fine: 4, level: 0.44 },
    subOsc: { enabled: true, waveform: 'sine', octave: -1, level: 0.08 },
    filter: { type: 'bandpass', cutoff: 1350, resonance: 3.8, drive: 0.02, keyTracking: 0.08, envelopeAmount: 0.06 },
    ampEnv: { attack: 1.2, decay: 1.8, sustain: 0.72, release: 2.6 },
    filterEnv: { attack: 1.6, decay: 1.8, sustain: 0.42, release: 1.8 },
    lfo1: { waveform: 'triangle', rate: 0.16, depth: 0.16, target: 'filterCutoff', sync: 'free', syncValue: '1/1' },
    vectorMixer: { x: 0.48, y: 0.18 },
    effects: [fx('analog-choir-bloom-reverb', 'reverb', 0.38, { decay: 2.8 })],
  }),
  preset('motion-pwm-haze', 'Motion PWM Haze', 'Pad', {
    oscA: { waveform: 'pulse', octave: 0, fine: -14, level: 0.66 },
    oscB: { waveform: 'pulse', octave: 0, fine: 14, level: 0.62 },
    subOsc: { enabled: false, level: 0 },
    noise: { enabled: true, kind: 'pink', level: 0.08 },
    filter: { type: 'notch', cutoff: 1800, resonance: 5.8, drive: 0.05, keyTracking: 0.12, envelopeAmount: -0.08 },
    ampEnv: { attack: 0.9, decay: 1.4, sustain: 0.7, release: 2.0 },
    filterEnv: { attack: 1.3, decay: 1.8, sustain: 0.48, release: 1.4 },
    lfo1: { waveform: 'sine', rate: 0.24, depth: 0.35, target: 'oscMix', sync: 'free', syncValue: '1/1' },
    vectorMixer: { x: 0.52, y: 0.08 },
  }),
  preset('organ-air-pad', 'Organ Air Pad', 'Pad', {
    oscA: { waveform: 'sine', octave: 0, level: 0.42 },
    oscB: { waveform: 'triangle', octave: 1, semitone: 7, level: 0.4 },
    subOsc: { enabled: true, waveform: 'sine', octave: -1, level: 0.16 },
    filter: { type: 'lowpass', cutoff: 6400, resonance: 0.7, drive: 0.02, keyTracking: 0.18, envelopeAmount: 0.02 },
    ampEnv: { attack: 0.32, decay: 0.8, sustain: 0.9, release: 1.1 },
    filterEnv: { attack: 0.3, decay: 0.8, sustain: 0.74, release: 0.8 },
    vectorMixer: { x: 0.34, y: 0.24 },
    effects: [fx('organ-air-pad-chorus', 'chorus', 0.24, { time: 0.032, feedback: 0.08 })],
  }),

  preset('rubber-band-pluck', 'Rubber Band Pluck', 'Pluck', {
    oscA: { waveform: 'triangle', octave: 0, level: 0.58 },
    oscB: { waveform: 'pulse', octave: 0, semitone: 7, fine: 4, level: 0.42 },
    subOsc: { enabled: false, level: 0 },
    filter: { type: 'bandpass', cutoff: 900, resonance: 13.4, drive: 0.08, keyTracking: 0.38, envelopeAmount: 0.3 },
    ampEnv: { attack: 0.001, decay: 0.2, sustain: 0.01, release: 0.12 },
    filterEnv: { attack: 0.001, decay: 0.18, sustain: 0.02, release: 0.1 },
    vectorMixer: { x: 0.38, y: 0 },
  }),
  preset('koto-click', 'Koto Click', 'Pluck', {
    oscA: { waveform: 'pulse', octave: 0, level: 0.5 },
    oscB: { waveform: 'sine', octave: 1, semitone: 5, fine: -2, level: 0.48 },
    subOsc: { enabled: false, level: 0 },
    filter: { type: 'highpass', cutoff: 760, resonance: 3.2, drive: 0.03, keyTracking: 0.3, envelopeAmount: 0.14 },
    ampEnv: { attack: 0.001, decay: 0.52, sustain: 0.03, release: 0.42 },
    filterEnv: { attack: 0.001, decay: 0.34, sustain: 0.08, release: 0.24 },
    vectorMixer: { x: 0.46, y: 0 },
    effects: [fx('koto-click-delay', 'delay', 0.18, { time: 0.19, feedback: 0.16 })],
  }),
  preset('mallet-thumb', 'Mallet Thumb', 'Pluck', {
    oscA: { waveform: 'sine', octave: 0, level: 0.54 },
    oscB: { waveform: 'triangle', octave: 0, semitone: 12, level: 0.36 },
    subOsc: { enabled: true, waveform: 'sine', octave: -1, level: 0.08 },
    filter: { type: 'lowpass', cutoff: 1450, resonance: 2.6, drive: 0.04, keyTracking: 0.22, envelopeAmount: 0.1 },
    ampEnv: { attack: 0.003, decay: 0.62, sustain: 0.08, release: 0.46 },
    filterEnv: { attack: 0.003, decay: 0.5, sustain: 0.16, release: 0.34 },
    vectorMixer: { x: 0.4, y: 0.08 },
  }),
  preset('glass-pick', 'Glass Pick', 'Pluck', {
    oscA: { waveform: 'wavetable', octave: 1, fine: -5, level: 0.48 },
    oscB: { waveform: 'sine', octave: 2, semitone: -12, fine: 5, level: 0.34 },
    subOsc: { enabled: false, level: 0 },
    filter: { type: 'bandpass', cutoff: 4200, resonance: 8.8, drive: 0.03, keyTracking: 0.24, envelopeAmount: 0.12 },
    ampEnv: { attack: 0.001, decay: 0.28, sustain: 0.02, release: 0.24 },
    filterEnv: { attack: 0.001, decay: 0.22, sustain: 0.04, release: 0.18 },
    vectorMixer: { x: 0.54, y: 0 },
    effects: [fx('glass-pick-reverb', 'reverb', 0.2, { decay: 1.2 })],
  }),
  preset('low-fi-key-pluck', 'Low-Fi Key Pluck', 'Pluck', {
    oscA: { waveform: 'square', octave: 0, fine: -6, level: 0.5 },
    oscB: { waveform: 'wavetable', octave: 0, fine: 6, level: 0.32 },
    noise: { enabled: true, kind: 'pink', level: 0.04 },
    filter: { type: 'lowpass', cutoff: 1900, resonance: 3.4, drive: 0.06, keyTracking: 0.2, envelopeAmount: 0.1 },
    ampEnv: { attack: 0.006, decay: 0.34, sustain: 0.08, release: 0.24 },
    filterEnv: { attack: 0.006, decay: 0.28, sustain: 0.16, release: 0.2 },
    vectorMixer: { x: 0.42, y: 0.04 },
    effects: [fx('low-fi-key-pluck-bitcrusher', 'bitcrusher', 0.16, { drive: 0.28 })],
  }),
  preset('stereo-echo-pluck', 'Stereo Echo Pluck', 'Pluck', {
    oscA: { waveform: 'triangle', octave: 0, fine: -2, level: 0.54 },
    oscB: { waveform: 'pulse', octave: 1, semitone: -5, fine: 2, level: 0.36 },
    subOsc: { enabled: false, level: 0 },
    filter: { type: 'notch', cutoff: 2400, resonance: 6.4, drive: 0.04, keyTracking: 0.28, envelopeAmount: -0.04 },
    ampEnv: { attack: 0.004, decay: 0.32, sustain: 0.08, release: 0.24 },
    filterEnv: { attack: 0.004, decay: 0.28, sustain: 0.12, release: 0.2 },
    lfo2: { waveform: 'sine', rate: 0.5, depth: 0.28, target: 'pan', sync: 'free', syncValue: '1/2' },
    vectorMixer: { x: 0.5, y: 0 },
    effects: [fx('stereo-echo-pluck-delay', 'delay', 0.26, { time: 0.28, feedback: 0.3 })],
  }),

  preset('temple-bell-long', 'Temple Bell Long', 'Bell', {
    oscA: { waveform: 'sine', octave: 0, level: 0.42 },
    oscB: { waveform: 'wavetable', octave: 1, semitone: 7, fine: -6, level: 0.52 },
    subOsc: { enabled: false, level: 0 },
    filter: { type: 'bandpass', cutoff: 1380, resonance: 8.2, drive: 0.04, keyTracking: 0.14, envelopeAmount: 0.08 },
    ampEnv: { attack: 0.004, decay: 2.4, sustain: 0.02, release: 2.6 },
    filterEnv: { attack: 0.004, decay: 1.2, sustain: 0.08, release: 1.2 },
    vectorMixer: { x: 0.6, y: 0 },
    effects: [fx('temple-bell-long-reverb', 'reverb', 0.34, { decay: 2.8 })],
  }),
  preset('digital-handbell', 'Digital Handbell', 'Bell', {
    oscA: { waveform: 'triangle', octave: 1, fine: -5, level: 0.44 },
    oscB: { waveform: 'wavetable', octave: 2, semitone: -5, fine: 5, level: 0.42 },
    subOsc: { enabled: false, level: 0 },
    filter: { type: 'highpass', cutoff: 1600, resonance: 3.8, drive: 0.02, keyTracking: 0.2, envelopeAmount: 0.04 },
    ampEnv: { attack: 0.006, decay: 1.4, sustain: 0.04, release: 1.5 },
    filterEnv: { attack: 0.006, decay: 0.8, sustain: 0.1, release: 0.7 },
    vectorMixer: { x: 0.54, y: 0 },
    effects: [fx('digital-handbell-chorus', 'chorus', 0.18, { time: 0.018, feedback: 0.08 })],
  }),
  preset('crystal-clock', 'Crystal Clock', 'Bell', {
    oscA: { waveform: 'pulse', octave: 2, level: 0.34 },
    oscB: { waveform: 'sine', octave: 2, semitone: 7, level: 0.32 },
    subOsc: { enabled: false, level: 0 },
    filter: { type: 'bandpass', cutoff: 5200, resonance: 12.2, drive: 0.02, keyTracking: 0.18, envelopeAmount: 0.08 },
    ampEnv: { attack: 0.001, decay: 0.62, sustain: 0.01, release: 0.72 },
    filterEnv: { attack: 0.001, decay: 0.4, sustain: 0.04, release: 0.36 },
    vectorMixer: { x: 0.48, y: 0 },
    effects: [fx('crystal-clock-delay', 'delay', 0.2, { time: 0.18, feedback: 0.22 })],
  }),
  preset('bell-tree-sparkle', 'Bell Tree Sparkle', 'Bell', {
    oscA: { waveform: 'wavetable', octave: 1, fine: -9, level: 0.5 },
    oscB: { waveform: 'triangle', octave: 2, semitone: 2, fine: 9, level: 0.28 },
    noise: { enabled: true, kind: 'white', level: 0.06 },
    filter: { type: 'highpass', cutoff: 2300, resonance: 2.6, drive: 0.01, keyTracking: 0.18, envelopeAmount: 0.08 },
    ampEnv: { attack: 0.002, decay: 1.1, sustain: 0.02, release: 1.4 },
    filterEnv: { attack: 0.002, decay: 0.72, sustain: 0.08, release: 0.7 },
    lfo2: { waveform: 'sine', rate: 0.7, depth: 0.42, target: 'pan', sync: 'free', syncValue: '1/2' },
    vectorMixer: { x: 0.56, y: 0.04 },
    effects: [fx('bell-tree-sparkle-reverb', 'reverb', 0.42, { decay: 3 })],
  }),
  preset('soft-ep-bell', 'Soft EP Bell', 'Bell', {
    oscA: { waveform: 'sine', octave: 0, level: 0.42 },
    oscB: { waveform: 'triangle', octave: 1, semitone: 12, fine: 2, level: 0.36 },
    subOsc: { enabled: true, waveform: 'sine', octave: -1, level: 0.06 },
    filter: { type: 'lowpass', cutoff: 4200, resonance: 1.4, drive: 0.02, keyTracking: 0.2, envelopeAmount: 0.03 },
    ampEnv: { attack: 0.012, decay: 1.0, sustain: 0.18, release: 1.2 },
    filterEnv: { attack: 0.012, decay: 0.8, sustain: 0.28, release: 0.72 },
    vectorMixer: { x: 0.42, y: 0.08 },
    effects: [fx('soft-ep-bell-chorus', 'chorus', 0.2, { time: 0.03, feedback: 0.1 })],
  }),
  preset('metallic-moonbell', 'Metallic Moonbell', 'Bell', {
    oscA: { waveform: 'wavetable', octave: 1, fine: -13, level: 0.48 },
    oscB: { waveform: 'pulse', octave: 2, semitone: -7, fine: 13, level: 0.34 },
    noise: { enabled: true, kind: 'pink', level: 0.04 },
    filter: { type: 'notch', cutoff: 3700, resonance: 15.2, drive: 0.04, keyTracking: 0.16, envelopeAmount: -0.04 },
    ampEnv: { attack: 0.002, decay: 1.2, sustain: 0.02, release: 1.5 },
    filterEnv: { attack: 0.002, decay: 0.72, sustain: 0.06, release: 0.6 },
    vectorMixer: { x: 0.58, y: 0.04 },
    effects: [fx('metallic-moonbell-phaser', 'phaser', 0.18, { frequency: 1200, q: 8 })],
  }),

  preset('cyber-arp-16', 'Cyber Arp 16', 'Sequence', {
    bpm: 138,
    oscA: { waveform: 'pulse', octave: 0, level: 0.62 },
    oscB: { waveform: 'wavetable', octave: 1, semitone: -12, level: 0.42 },
    filter: { type: 'highpass', cutoff: 900, resonance: 4.4, drive: 0.08, keyTracking: 0.22, envelopeAmount: 0.18 },
    ampEnv: { attack: 0.001, decay: 0.14, sustain: 0.12, release: 0.08 },
    filterEnv: { attack: 0.001, decay: 0.18, sustain: 0.08, release: 0.08 },
    waveSequencer: { enabled: true, tempoSync: true },
    lfo1: { waveform: 'square', rate: 6, depth: 0.2, target: 'filterCutoff', sync: 'tempo', syncValue: '1/8' },
    vectorMixer: { x: 0.54, y: 0 },
    effects: [fx('cyber-arp-16-delay', 'delay', 0.22, { time: 0.18, feedback: 0.3 })],
  }),
  preset('polyrhythm-pulse', 'Polyrhythm Pulse', 'Sequence', {
    bpm: 127,
    oscA: { waveform: 'sawtooth', octave: 0, fine: -5, level: 0.64 },
    oscB: { waveform: 'square', octave: 0, fine: 5, level: 0.44 },
    subOsc: { enabled: true, waveform: 'square', octave: -1, level: 0.12 },
    filter: { type: 'notch', cutoff: 1700, resonance: 7.8, drive: 0.08, keyTracking: 0.16, envelopeAmount: -0.12 },
    ampEnv: { attack: 0.002, decay: 0.2, sustain: 0.16, release: 0.12 },
    filterEnv: { attack: 0.002, decay: 0.24, sustain: 0.12, release: 0.1 },
    waveSequencer: { enabled: true, tempoSync: true },
    lfo2: { waveform: 'sine', rate: 0.5, depth: 0.48, target: 'pan', sync: 'tempo', syncValue: '1/2' },
    vectorMixer: { x: 0.48, y: 0.08 },
  }),
  preset('minor-machine-run', 'Minor Machine Run', 'Sequence', {
    bpm: 146,
    oscA: { waveform: 'wavetable', octave: 0, level: 0.58 },
    oscB: { waveform: 'pulse', octave: 0, semitone: 3, level: 0.42 },
    subOsc: { enabled: false, level: 0 },
    filter: { type: 'bandpass', cutoff: 2300, resonance: 8.4, drive: 0.1, keyTracking: 0.24, envelopeAmount: 0.24 },
    ampEnv: { attack: 0.001, decay: 0.16, sustain: 0.1, release: 0.1 },
    filterEnv: { attack: 0.001, decay: 0.18, sustain: 0.08, release: 0.08 },
    waveSequencer: { enabled: true, tempoSync: true },
    vectorMixer: { x: 0.46, y: 0 },
    effects: [fx('minor-machine-run-bitcrusher', 'bitcrusher', 0.14, { drive: 0.28 })],
  }),
  preset('glass-step-delay', 'Glass Step Delay', 'Sequence', {
    bpm: 122,
    oscA: { waveform: 'triangle', octave: 0, level: 0.5 },
    oscB: { waveform: 'wavetable', octave: 1, fine: 4, level: 0.42 },
    filter: { type: 'highpass', cutoff: 1100, resonance: 3.4, drive: 0.03, keyTracking: 0.2, envelopeAmount: 0.1 },
    ampEnv: { attack: 0.002, decay: 0.22, sustain: 0.08, release: 0.22 },
    filterEnv: { attack: 0.002, decay: 0.2, sustain: 0.12, release: 0.16 },
    waveSequencer: { enabled: true, tempoSync: true },
    vectorMixer: { x: 0.56, y: 0 },
    effects: [fx('glass-step-delay-delay', 'delay', 0.34, { time: 0.36, feedback: 0.38 })],
  }),
  preset('sub-ratchet-seq', 'Sub Ratchet Seq', 'Sequence', {
    bpm: 152,
    oscA: { waveform: 'pulse', octave: -1, level: 0.6 },
    oscB: { waveform: 'square', octave: -1, semitone: 12, level: 0.32 },
    subOsc: { enabled: true, waveform: 'sine', octave: -2, level: 0.36 },
    filter: { type: 'ladder', cutoff: 840, resonance: 9.2, drive: 0.28, keyTracking: 0.14, envelopeAmount: 0.36 },
    ampEnv: { attack: 0.001, decay: 0.1, sustain: 0.18, release: 0.07 },
    filterEnv: { attack: 0.001, decay: 0.12, sustain: 0.06, release: 0.06 },
    waveSequencer: { enabled: true, tempoSync: true },
    vectorMixer: { x: 0.32, y: 0.24 },
    effects: [fx('sub-ratchet-seq-compressor', 'compressor', 0.68, { threshold: -24, ratio: 6 })],
  }),
  preset('vector-step-cloud', 'Vector Step Cloud', 'Sequence', {
    bpm: 104,
    oscA: { waveform: 'sawtooth', octave: 0, fine: -9, level: 0.54 },
    oscB: { waveform: 'wavetable', octave: 0, semitone: 7, fine: 9, level: 0.48 },
    noise: { enabled: true, kind: 'pink', level: 0.08 },
    filter: { type: 'lowpass', cutoff: 2000, resonance: 2.2, drive: 0.04, keyTracking: 0.12, envelopeAmount: 0.12 },
    ampEnv: { attack: 0.02, decay: 0.42, sustain: 0.28, release: 0.4 },
    filterEnv: { attack: 0.02, decay: 0.48, sustain: 0.24, release: 0.32 },
    waveSequencer: { enabled: true, tempoSync: true },
    lfo1: { waveform: 'triangle', rate: 0.25, depth: 0.44, target: 'wavePosition', sync: 'tempo', syncValue: '1/1' },
    vectorMixer: { x: 0.5, y: 0.2 },
    effects: [fx('vector-step-cloud-reverb', 'reverb', 0.3, { decay: 2.2 })],
  }),

  preset('rain-window-drone', 'Rain Window Drone', 'Ambient', {
    oscA: { waveform: 'sine', octave: -1, fine: -7, level: 0.34 },
    oscB: { waveform: 'wavetable', octave: 0, semitone: 7, fine: 7, level: 0.42 },
    noise: { enabled: true, kind: 'pink', level: 0.22 },
    filter: { type: 'bandpass', cutoff: 980, resonance: 3.2, drive: 0.02, keyTracking: 0.04, envelopeAmount: 0.04 },
    ampEnv: { attack: 2.0, decay: 2.4, sustain: 0.74, release: 3.6 },
    filterEnv: { attack: 2.4, decay: 2.8, sustain: 0.5, release: 2.6 },
    lfo1: { waveform: 'sine', rate: 0.08, depth: 0.24, target: 'filterCutoff', sync: 'free', syncValue: '1/1' },
    vectorMixer: { x: 0.58, y: 0.54 },
    effects: [fx('rain-window-drone-reverb', 'reverb', 0.48, { decay: 4 })],
  }),
  preset('aurora-swarm', 'Aurora Swarm', 'Ambient', {
    oscA: { waveform: 'sawtooth', octave: 0, fine: -18, level: 0.36 },
    oscB: { waveform: 'wavetable', octave: 1, semitone: -5, fine: 18, level: 0.4 },
    subOsc: { enabled: true, waveform: 'sine', octave: -1, level: 0.08 },
    noise: { enabled: true, kind: 'pink', level: 0.1 },
    filter: { type: 'notch', cutoff: 2100, resonance: 6.2, drive: 0.03, keyTracking: 0.06, envelopeAmount: -0.06 },
    ampEnv: { attack: 2.4, decay: 2.6, sustain: 0.72, release: 3.8 },
    filterEnv: { attack: 2.6, decay: 3.0, sustain: 0.46, release: 2.4 },
    lfo2: { waveform: 'sine', rate: 0.12, depth: 0.38, target: 'pan', sync: 'free', syncValue: '1/1' },
    vectorMixer: { x: 0.52, y: 0.18 },
    effects: [fx('aurora-swarm-chorus', 'chorus', 0.3, { time: 0.034, feedback: 0.12 }), fx('aurora-swarm-reverb', 'reverb', 0.44, { decay: 3.6 })],
  }),
  preset('dusty-cathedral', 'Dusty Cathedral', 'Ambient', {
    oscA: { waveform: 'triangle', octave: -1, level: 0.42 },
    oscB: { waveform: 'sine', octave: 0, semitone: 12, level: 0.34 },
    subOsc: { enabled: true, waveform: 'sine', octave: -2, level: 0.12 },
    noise: { enabled: true, kind: 'pink', level: 0.06 },
    filter: { type: 'lowpass', cutoff: 1800, resonance: 1.0, drive: 0.03, keyTracking: 0.08, envelopeAmount: 0.03 },
    ampEnv: { attack: 1.6, decay: 2.2, sustain: 0.82, release: 4.0 },
    filterEnv: { attack: 2.0, decay: 2.2, sustain: 0.64, release: 2.8 },
    vectorMixer: { x: 0.32, y: 0.2 },
    effects: [fx('dusty-cathedral-reverb', 'reverb', 0.55, { decay: 4.5 })],
  }),
  preset('satellite-choir', 'Satellite Choir', 'Ambient', {
    oscA: { waveform: 'wavetable', octave: 0, fine: -4, level: 0.46 },
    oscB: { waveform: 'wavetable', octave: 1, semitone: -12, fine: 4, level: 0.46 },
    subOsc: { enabled: false, level: 0 },
    filter: { type: 'bandpass', cutoff: 1700, resonance: 4.6, drive: 0.02, keyTracking: 0.08, envelopeAmount: 0.02 },
    ampEnv: { attack: 1.8, decay: 2.4, sustain: 0.76, release: 3.2 },
    filterEnv: { attack: 2.2, decay: 2.6, sustain: 0.5, release: 2.2 },
    lfo1: { waveform: 'triangle', rate: 0.18, depth: 0.18, target: 'oscMix', sync: 'free', syncValue: '1/1' },
    vectorMixer: { x: 0.5, y: 0.06 },
    effects: [fx('satellite-choir-reverb', 'reverb', 0.42, { decay: 3.4 })],
  }),
  preset('warm-tape-horizon', 'Warm Tape Horizon', 'Ambient', {
    oscA: { waveform: 'sawtooth', octave: -1, fine: -12, level: 0.36 },
    oscB: { waveform: 'triangle', octave: 0, fine: 12, level: 0.32 },
    subOsc: { enabled: true, waveform: 'sine', octave: -2, level: 0.1 },
    noise: { enabled: true, kind: 'pink', level: 0.08 },
    filter: { type: 'lowpass', cutoff: 1250, resonance: 1.4, drive: 0.08, keyTracking: 0.04, envelopeAmount: 0.04 },
    ampEnv: { attack: 1.5, decay: 2.0, sustain: 0.78, release: 3.4 },
    filterEnv: { attack: 1.8, decay: 2.4, sustain: 0.52, release: 2.2 },
    lfo1: { waveform: 'sine', rate: 0.11, depth: 0.04, target: 'pitch', sync: 'free', syncValue: '1/1' },
    vectorMixer: { x: 0.38, y: 0.22 },
    effects: [fx('warm-tape-horizon-reverb', 'reverb', 0.32, { decay: 2.8 }), fx('warm-tape-horizon-distortion', 'distortion', 0.08, { drive: 0.18 })],
  }),
  preset('deep-abyss-pad', 'Deep Abyss Pad', 'Ambient', {
    oscA: { waveform: 'sine', octave: -1, level: 0.38 },
    oscB: { waveform: 'wavetable', octave: 0, semitone: -7, level: 0.34 },
    subOsc: { enabled: true, waveform: 'sine', octave: -2, level: 0.18 },
    noise: { enabled: true, kind: 'pink', level: 0.1 },
    filter: { type: 'lowpass', cutoff: 780, resonance: 2.0, drive: 0.04, keyTracking: 0.04, envelopeAmount: 0.02 },
    ampEnv: { attack: 2.6, decay: 2.8, sustain: 0.8, release: 4.0 },
    filterEnv: { attack: 3.0, decay: 3.0, sustain: 0.58, release: 3.0 },
    vectorMixer: { x: 0.44, y: 0.34 },
    effects: [fx('deep-abyss-pad-reverb', 'reverb', 0.5, { decay: 4.2 })],
  }),

  preset('reverse-riser-noise', 'Reverse Riser Noise', 'FX', {
    oscA: { waveform: 'sine', octave: 1, level: 0.06 },
    oscB: { waveform: 'triangle', octave: 2, level: 0.04 },
    noise: { enabled: true, kind: 'white', level: 0.64 },
    filter: { type: 'highpass', cutoff: 900, resonance: 8.4, drive: 0.04, keyTracking: 0.02, envelopeAmount: 0.9 },
    ampEnv: { attack: 1.8, decay: 0.6, sustain: 0.7, release: 1.2 },
    filterEnv: { attack: 2.2, decay: 0.5, sustain: 0.84, release: 0.8 },
    lfo1: { waveform: 'sawtooth', rate: 0.24, depth: 0.36, target: 'filterCutoff', sync: 'free', syncValue: '1/1' },
    vectorMixer: { x: 0.86, y: 0.9 },
    effects: [fx('reverse-riser-noise-reverb', 'reverb', 0.34, { decay: 2.6 })],
  }),
  preset('impact-thunder-hit', 'Impact Thunder Hit', 'FX', {
    oscA: { waveform: 'sine', octave: -1, level: 0.5 },
    oscB: { waveform: 'sawtooth', octave: -1, fine: -16, level: 0.34 },
    subOsc: { enabled: true, waveform: 'sine', octave: -2, level: 0.32 },
    noise: { enabled: true, kind: 'pink', level: 0.28 },
    filter: { type: 'lowpass', cutoff: 640, resonance: 4.4, drive: 0.32, keyTracking: 0.02, envelopeAmount: -0.18 },
    ampEnv: { attack: 0.001, decay: 1.1, sustain: 0.05, release: 1.4 },
    filterEnv: { attack: 0.001, decay: 0.7, sustain: 0.08, release: 0.8 },
    vectorMixer: { x: 0.34, y: 0.62 },
    effects: [fx('impact-thunder-hit-distortion', 'distortion', 0.28, { drive: 0.42 }), fx('impact-thunder-hit-reverb', 'reverb', 0.28, { decay: 2.1 })],
  }),
  preset('servo-lift', 'Servo Lift', 'FX', {
    oscA: { waveform: 'pulse', octave: 0, fine: -18, level: 0.48 },
    oscB: { waveform: 'square', octave: 1, fine: 18, level: 0.42 },
    noise: { enabled: true, kind: 'white', level: 0.08 },
    filter: { type: 'bandpass', cutoff: 1900, resonance: 14.2, drive: 0.16, keyTracking: 0.08, envelopeAmount: 0.42 },
    ampEnv: { attack: 0.02, decay: 0.58, sustain: 0.1, release: 0.38 },
    filterEnv: { attack: 0.12, decay: 0.44, sustain: 0.12, release: 0.24 },
    lfo1: { waveform: 'sawtooth', rate: 7.2, depth: 0.1, target: 'pitch', sync: 'free', syncValue: '1/8' },
    vectorMixer: { x: 0.52, y: 0.1 },
  }),
  preset('digital-glitch-pop', 'Digital Glitch Pop', 'FX', {
    oscA: { waveform: 'wavetable', octave: 2, fine: -28, level: 0.42 },
    oscB: { waveform: 'pulse', octave: 1, semitone: 6, fine: 28, level: 0.38 },
    noise: { enabled: true, kind: 'white', level: 0.12 },
    filter: { type: 'highpass', cutoff: 3200, resonance: 12.8, drive: 0.08, keyTracking: 0.1, envelopeAmount: 0.28 },
    ampEnv: { attack: 0.001, decay: 0.12, sustain: 0.01, release: 0.08 },
    filterEnv: { attack: 0.001, decay: 0.1, sustain: 0.02, release: 0.06 },
    vectorMixer: { x: 0.56, y: 0.12 },
    effects: [fx('digital-glitch-pop-bitcrusher', 'bitcrusher', 0.34, { drive: 0.62 })],
  }),
  preset('alien-transmission', 'Alien Transmission', 'FX', {
    oscA: { waveform: 'wavetable', octave: 0, fine: -33, level: 0.42 },
    oscB: { waveform: 'pulse', octave: 1, semitone: -7, fine: 31, level: 0.38 },
    noise: { enabled: true, kind: 'white', level: 0.18 },
    filter: { type: 'bandpass', cutoff: 1320, resonance: 17.4, drive: 0.14, keyTracking: 0.05, envelopeAmount: -0.12 },
    ampEnv: { attack: 0.02, decay: 0.38, sustain: 0.18, release: 0.42 },
    filterEnv: { attack: 0.04, decay: 0.3, sustain: 0.14, release: 0.28 },
    lfo1: { waveform: 'square', rate: 9.6, depth: 0.22, target: 'filterCutoff', sync: 'free', syncValue: '1/16' },
    vectorMixer: { x: 0.5, y: 0.24 },
    effects: [fx('alien-transmission-phaser', 'phaser', 0.28, { frequency: 880, q: 12 })],
  }),
  preset('airlock-release', 'Airlock Release', 'FX', {
    oscA: { waveform: 'sine', octave: 0, level: 0.08 },
    oscB: { waveform: 'triangle', octave: 0, level: 0.04 },
    noise: { enabled: true, kind: 'pink', level: 0.6 },
    filter: { type: 'bandpass', cutoff: 620, resonance: 4.2, drive: 0.03, keyTracking: 0.02, envelopeAmount: -0.24 },
    ampEnv: { attack: 0.2, decay: 1.3, sustain: 0.34, release: 1.8 },
    filterEnv: { attack: 0.2, decay: 1.2, sustain: 0.2, release: 1.2 },
    vectorMixer: { x: 0.78, y: 0.88 },
    effects: [fx('airlock-release-reverb', 'reverb', 0.28, { decay: 2.2 })],
  }),

  preset('granular-shards', 'Granular Shards', 'Experimental', {
    oscA: { waveform: 'wavetable', octave: 1, fine: -38, level: 0.48 },
    oscB: { waveform: 'pulse', octave: 2, semitone: -11, fine: 34, level: 0.34 },
    noise: { enabled: true, kind: 'white', level: 0.1 },
    filter: { type: 'notch', cutoff: 3900, resonance: 18.2, drive: 0.1, keyTracking: 0.1, envelopeAmount: -0.16 },
    ampEnv: { attack: 0.001, decay: 0.24, sustain: 0.08, release: 0.18 },
    filterEnv: { attack: 0.001, decay: 0.18, sustain: 0.08, release: 0.12 },
    lfo1: { waveform: 'wavetable', rate: 11, depth: 0.12, target: 'pitch', sync: 'free', syncValue: '1/16' },
    vectorMixer: { x: 0.56, y: 0.08 },
    effects: [fx('granular-shards-bitcrusher', 'bitcrusher', 0.24, { drive: 0.54 })],
  }),
  preset('unstable-vector-lab', 'Unstable Vector Lab', 'Experimental', {
    oscA: { waveform: 'pulse', octave: 0, fine: -47, level: 0.42 },
    oscB: { waveform: 'wavetable', octave: 1, semitone: 4, fine: 43, level: 0.48 },
    subOsc: { enabled: true, waveform: 'square', octave: -1, level: 0.1 },
    noise: { enabled: true, kind: 'pink', level: 0.08 },
    filter: { type: 'bandpass', cutoff: 1600, resonance: 13.2, drive: 0.12, keyTracking: 0.08, envelopeAmount: 0.08 },
    ampEnv: { attack: 0.008, decay: 0.46, sustain: 0.24, release: 0.38 },
    filterEnv: { attack: 0.006, decay: 0.34, sustain: 0.16, release: 0.24 },
    lfo1: { waveform: 'triangle', rate: 0.42, depth: 0.5, target: 'wavePosition', sync: 'free', syncValue: '1/2' },
    vectorMixer: { x: 0.52, y: 0.22 },
    effects: [fx('unstable-vector-lab-phaser', 'phaser', 0.24, { frequency: 640, q: 10 })],
  }),
  preset('bitrot-organ', 'Bitrot Organ', 'Experimental', {
    oscA: { waveform: 'square', octave: 0, fine: -19, level: 0.5 },
    oscB: { waveform: 'square', octave: 1, semitone: -12, fine: 17, level: 0.44 },
    subOsc: { enabled: true, waveform: 'triangle', octave: -1, level: 0.14 },
    filter: { type: 'lowpass', cutoff: 2600, resonance: 2.4, drive: 0.1, keyTracking: 0.14, envelopeAmount: 0.04 },
    ampEnv: { attack: 0.03, decay: 0.4, sustain: 0.64, release: 0.46 },
    filterEnv: { attack: 0.03, decay: 0.42, sustain: 0.42, release: 0.32 },
    vectorMixer: { x: 0.38, y: 0.12 },
    effects: [fx('bitrot-organ-bitcrusher', 'bitcrusher', 0.3, { drive: 0.44 }), fx('bitrot-organ-chorus', 'chorus', 0.18, { time: 0.024, feedback: 0.12 })],
  }),
  preset('folded-metal-breath', 'Folded Metal Breath', 'Experimental', {
    oscA: { waveform: 'wavetable', octave: 0, fine: -22, level: 0.42 },
    oscB: { waveform: 'triangle', octave: 1, semitone: 6, fine: 21, level: 0.36 },
    noise: { enabled: true, kind: 'pink', level: 0.18 },
    filter: { type: 'notch', cutoff: 2500, resonance: 16.8, drive: 0.18, keyTracking: 0.06, envelopeAmount: -0.1 },
    ampEnv: { attack: 0.08, decay: 0.7, sustain: 0.3, release: 0.74 },
    filterEnv: { attack: 0.06, decay: 0.52, sustain: 0.18, release: 0.42 },
    lfo2: { waveform: 'sine', rate: 0.32, depth: 0.36, target: 'pan', sync: 'free', syncValue: '1/2' },
    vectorMixer: { x: 0.54, y: 0.26 },
    effects: [fx('folded-metal-breath-flanger', 'flanger', 0.24, { time: 0.01, feedback: 0.48 })],
  }),
  preset('numbers-station', 'Numbers Station', 'Experimental', {
    oscA: { waveform: 'pulse', octave: 1, fine: -12, level: 0.34 },
    oscB: { waveform: 'sine', octave: 0, semitone: 11, fine: 12, level: 0.32 },
    noise: { enabled: true, kind: 'white', level: 0.28 },
    filter: { type: 'bandpass', cutoff: 1220, resonance: 10.6, drive: 0.08, keyTracking: 0.04, envelopeAmount: -0.04 },
    ampEnv: { attack: 0.01, decay: 0.28, sustain: 0.18, release: 0.22 },
    filterEnv: { attack: 0.01, decay: 0.22, sustain: 0.16, release: 0.18 },
    lfo1: { waveform: 'square', rate: 7.5, depth: 0.18, target: 'ampLevel', sync: 'free', syncValue: '1/16' },
    vectorMixer: { x: 0.44, y: 0.34 },
    effects: [fx('numbers-station-delay', 'delay', 0.22, { time: 0.12, feedback: 0.2 })],
  }),
  preset('chaos-mallet', 'Chaos Mallet', 'Experimental', {
    oscA: { waveform: 'triangle', octave: 0, fine: -15, level: 0.46 },
    oscB: { waveform: 'wavetable', octave: 1, semitone: 8, fine: 19, level: 0.48 },
    noise: { enabled: true, kind: 'white', level: 0.08 },
    filter: { type: 'notch', cutoff: 3200, resonance: 14.4, drive: 0.08, keyTracking: 0.12, envelopeAmount: 0.1 },
    ampEnv: { attack: 0.002, decay: 0.56, sustain: 0.06, release: 0.48 },
    filterEnv: { attack: 0.002, decay: 0.36, sustain: 0.08, release: 0.28 },
    lfo1: { waveform: 'wavetable', rate: 3.7, depth: 0.1, target: 'pitch', sync: 'free', syncValue: '1/8' },
    vectorMixer: { x: 0.58, y: 0.12 },
    effects: [fx('chaos-mallet-reverb', 'reverb', 0.24, { decay: 1.8 })],
  }),
  ...expandedFactoryPresets,
];
